--- 
document: 
  name: "Template di conversione di Docs Italia"
  description: "Modello ottenuto dalla conversione di un documento con il convertitore web di Docs Italia"
  tags: 
    - Docs Italia
    - template
